blank_issues_enabled: false
contact_links:
  - name: XLibre on Fedora/Enterprise Linux Discussions
    url: https://github.com/X11Libre/packaging/discussions/categories/xlibre-on-fedora-el
    about: Please ask and answer questions here.
